const STORAGE_KEY = 'westlakeTreeExpertsAppV4';
const money = n => `$${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const fmtDate = d => d ? new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'}) : '';
const uid = prefix => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2,7)}`;
const defaultState = {customers:[],invoices:[],estimates:[],jobs:[],payments:[]};
let state = load(); let currentPage='home'; let currentFilter='all';
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaultState}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function app(){return document.getElementById('app')}
function setPage(page, filter='all'){currentPage=page; currentFilter=filter; document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); render(); window.scrollTo(0,0)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
function customerName(id){return state.customers.find(c=>c.id===id)?.name || 'No customer selected'}
function invoiceBalance(inv){return Math.max(0, Number(inv.total||0)-Number(inv.paid||0))}
function invoiceStatus(inv){return invoiceBalance(inv)<=0 ? 'Paid' : 'Open'}
function estimateStatus(est){return est.status || 'Open'}
function calcRevenueMonth(){const now=new Date();return state.payments.filter(p=>{const d=new Date(`${p.date}T12:00:00`);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,p)=>s+Number(p.amount||0),0)}
function render(){({home,customers,invoices,estimates,jobs,reports}[currentPage]||home)()}
function home(){const openInvoices=state.invoices.filter(i=>invoiceStatus(i)==='Open'); const paidInvoices=state.invoices.filter(i=>invoiceStatus(i)==='Paid'); const openEstimates=state.estimates.filter(e=>estimateStatus(e)!=='Approved'&&estimateStatus(e)!=='Rejected'); const scheduled=state.jobs.filter(j=>j.date).sort((a,b)=>a.date.localeCompare(b.date));
app().innerHTML=`<section class="grid">
  <div class="card metric" onclick="setPage('reports')"><div class="label">Revenue This Month</div><div class="value">${money(calcRevenueMonth())}</div></div>
  <div class="card metric" onclick="setPage('invoices','open')"><div class="label">Open Invoices</div><div class="value">${openInvoices.length}</div></div>
  <div class="card metric" onclick="setPage('invoices','paid')"><div class="label">Paid Invoices</div><div class="value">${paidInvoices.length}</div></div>
  <div class="card metric" onclick="setPage('estimates','open')"><div class="label">Open Estimates</div><div class="value">${openEstimates.length}</div></div>
  <div class="card metric" onclick="setPage('jobs','scheduled')"><div class="label">Jobs Scheduled</div><div class="value">${scheduled.length}</div></div>
</section>
<div class="section-title"><h2>Quick Actions</h2></div><div class="actions">
  <button class="btn primary" onclick="invoiceForm()">New Invoice</button><button class="btn" onclick="customerForm()">New Customer</button><button class="btn" onclick="estimateForm()">New Estimate</button><button class="btn" onclick="paymentForm()">Record Payment</button>
</div>
${preview('Recent Customers',state.customers.slice(-5).reverse().map(c=>`<div class="row"><b>${c.name}</b><span class="muted">${c.phone||''} ${c.propertyAddress? '· '+c.propertyAddress:''}</span></div>`).join(''))}
${preview('Recent Invoices',state.invoices.slice(-5).reverse().map(invoiceRow).join(''))}
${preview('Upcoming Jobs',scheduled.filter(j=>new Date(`${j.date}T12:00:00`)<=new Date(Date.now()+7*864e5)).map(jobRow).join(''))}`}
function preview(title,html){return `<div class="section-title"><h2>${title}</h2></div><div class="list">${html||'<div class="empty">No records yet.</div>'}</div>`}
function customers(){app().innerHTML=`<div class="section-title"><h2>Customers</h2><button class="btn primary" onclick="customerForm()">New Customer</button></div><div class="list">${state.customers.map(c=>`<div class="row"><div class="row-top"><b>${c.name}</b><button class="linkish" onclick="customerForm('${c.id}')">Edit</button></div><div class="muted">Phone: ${c.phone||'—'} · Email: ${c.email||'—'}</div><div class="muted">Property: ${c.propertyAddress||'—'}</div><div class="muted">Last Service: ${fmtDate(c.lastServiceDate)||'—'} · Lifetime Revenue: ${money(state.invoices.filter(i=>i.customerId===c.id).reduce((s,i)=>s+Number(i.paid||0),0))}</div><p>${c.notes||''}</p></div>`).join('')||'<div class="empty">No customers yet.</div>'}</div>`}
function invoices(){let rows=[...state.invoices]; if(currentFilter==='open') rows=rows.filter(i=>invoiceStatus(i)==='Open'); if(currentFilter==='paid') rows=rows.filter(i=>invoiceStatus(i)==='Paid'); rows.sort((a,b)=>(b.date||'').localeCompare(a.date||'')); app().innerHTML=`<div class="section-title"><h2>${currentFilter==='open'?'Open Invoices':currentFilter==='paid'?'Paid Invoices':'Invoices'}</h2><button class="btn primary" onclick="invoiceForm()">New Invoice</button></div>${filterButtons('invoices')}<div class="list">${rows.map(invoiceRow).join('')||'<div class="empty">No invoices found.</div>'}</div>`}
function estimates(){let rows=[...state.estimates]; if(currentFilter==='open') rows=rows.filter(e=>estimateStatus(e)!=='Approved'&&estimateStatus(e)!=='Rejected'); rows.sort((a,b)=>(b.date||'').localeCompare(a.date||'')); app().innerHTML=`<div class="section-title"><h2>${currentFilter==='open'?'Open Estimates':'Estimates'}</h2><button class="btn primary" onclick="estimateForm()">New Estimate</button></div>${filterButtons('estimates')}<div class="list">${rows.map(estimateRow).join('')||'<div class="empty">No estimates found.</div>'}</div>`}
function jobs(){let rows=[...state.jobs]; if(currentFilter==='scheduled') rows=rows.filter(j=>j.date); rows.sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')); app().innerHTML=`<div class="section-title"><h2>${currentFilter==='scheduled'?'Scheduled Jobs':'Jobs'}</h2><button class="btn primary" onclick="jobForm()">New Job</button></div>${filterButtons('jobs')}<div class="list">${rows.map(jobRow).join('')||'<div class="empty">No jobs found.</div>'}</div>`}
function filterButtons(page){return `<div class="filter-bar"><button class="btn ${currentFilter==='all'?'primary':''}" onclick="setPage('${page}','all')">All</button>${page==='invoices'?`<button class="btn ${currentFilter==='open'?'primary':''}" onclick="setPage('invoices','open')">Open</button><button class="btn ${currentFilter==='paid'?'primary':''}" onclick="setPage('invoices','paid')">Paid</button>`:''}${page==='estimates'?`<button class="btn ${currentFilter==='open'?'primary':''}" onclick="setPage('estimates','open')">Open</button>`:''}${page==='jobs'?`<button class="btn ${currentFilter==='scheduled'?'primary':''}" onclick="setPage('jobs','scheduled')">Scheduled</button>`:''}<button class="btn secondary" onclick="setPage('home')">Home</button></div>`}
function invoiceRow(i){const st=invoiceStatus(i); return `<div class="row"><div class="row-top"><b>${customerName(i.customerId)} — Invoice #${i.number}</b><span class="pill ${st.toLowerCase()}">${st}</span></div><div class="muted">Date: ${fmtDate(i.date)} · Service: ${i.service||'—'}</div><div>Total: ${money(i.total)} · Paid: ${money(i.paid)} · Balance: ${money(invoiceBalance(i))}</div><div class="actions"><button class="btn" onclick="invoiceForm('${i.id}')">Edit</button><button class="btn" onclick="paymentForm('${i.id}')">Record Payment</button><button class="btn" onclick="printRecord('invoices','${i.id}')">Print</button><button class="btn danger" onclick="del('invoices','${i.id}')">Delete</button></div></div>`}
function estimateRow(e){return `<div class="row"><div class="row-top"><b>${customerName(e.customerId)} — Estimate #${e.number}</b><span class="pill open">${estimateStatus(e)}</span></div><div class="muted">Date: ${fmtDate(e.date)} · Service: ${e.service||'—'}</div><div>Total: ${money(e.total)}</div><div class="actions"><button class="btn" onclick="estimateForm('${e.id}')">Edit</button><button class="btn" onclick="approveEstimate('${e.id}')">Approve + Schedule</button><button class="btn" onclick="printRecord('estimates','${e.id}')">Print</button><button class="btn danger" onclick="del('estimates','${e.id}')">Delete</button></div></div>`}
function jobRow(j){return `<div class="row"><div class="row-top"><b>${customerName(j.customerId)} — ${j.title||'Job'}</b><span class="pill scheduled">${j.date?'Scheduled':'Unscheduled'}</span></div><div class="muted">Scheduled: ${fmtDate(j.date)||'Not scheduled'} · From: ${j.estimateNumber?`Estimate #${j.estimateNumber}`:'Manual'}</div><p>${j.notes||''}</p><div class="actions"><button class="btn" onclick="jobForm('${j.id}')">Edit</button><button class="btn danger" onclick="del('jobs','${j.id}')">Delete</button></div></div>`}
function customerOptions(selected=''){return `<option value="">Select customer</option>${state.customers.map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>${c.name}</option>`).join('')}`}
function customerForm(id){const c=state.customers.find(x=>x.id===id)||{}; app().innerHTML=formWrap(id?'Edit Customer':'New Customer',`<label>Name<input id="name" value="${c.name||''}"></label><label>Phone<input id="phone" value="${c.phone||''}"></label><label>Email<input id="email" value="${c.email||''}"></label><label>Property Address<input id="propertyAddress" value="${c.propertyAddress||''}"></label><label>Last Service Date<input type="date" id="lastServiceDate" value="${c.lastServiceDate||''}"></label><label class="full">Notes<textarea id="notes">${c.notes||''}</textarea></label>`,()=>{let obj={id:id||uid('cust'),name:val('name'),phone:val('phone'),email:val('email'),propertyAddress:val('propertyAddress'),lastServiceDate:val('lastServiceDate'),notes:val('notes')}; upsert('customers',obj); setPage('customers')})}
function invoiceForm(id){recordForm('invoices',id)} function estimateForm(id){recordForm('estimates',id)}
function recordForm(type,id){const r=state[type].find(x=>x.id===id)||{date:new Date().toISOString().slice(0,10),paid:0,discount:0,tax:0}; const isInv=type==='invoices'; app().innerHTML=formWrap(id?`Edit ${isInv?'Invoice':'Estimate'}`:`New ${isInv?'Invoice':'Estimate'}`,`<label>Customer<select id="customerId">${customerOptions(r.customerId)}</select></label><label>${isInv?'Invoice':'Estimate'} #<input id="number" value="${r.number||nextNumber(type)}"></label><label>Date<input type="date" id="date" value="${r.date||''}"></label><label>Service<select id="service"><option ${r.service==='Tree Service'?'selected':''}>Tree Service</option><option ${r.service==='Lawn Service'?'selected':''}>Lawn Service</option><option ${r.service==='Mulching'?'selected':''}>Mulching</option><option ${r.service==='Seeding'?'selected':''}>Seeding</option><option ${r.service==='Other'?'selected':''}>Other</option></select></label><label>Description<input id="description" value="${r.description||''}"></label><label>Amount Charged<input type="number" step="0.01" id="amount" value="${r.amount||r.total||0}"></label><label>Discount<input type="number" step="0.01" id="discount" value="${r.discount||0}"></label><label>Tax<input type="number" step="0.01" id="tax" value="${r.tax||0}"></label>${isInv?`<label>Already Paid<input type="number" step="0.01" id="paid" value="${r.paid||0}"></label>`:`<label>Status<select id="status"><option ${estimateStatus(r)==='Open'?'selected':''}>Open</option><option ${estimateStatus(r)==='Approved'?'selected':''}>Approved</option><option ${estimateStatus(r)==='Rejected'?'selected':''}>Rejected</option></select></label>`}<label class="full">Notes<textarea id="notes">${r.notes||''}</textarea></label>`,()=>{const amount=Number(val('amount')), discount=Number(val('discount')), tax=Number(val('tax')); let obj={id:id||uid(isInv?'inv':'est'),customerId:val('customerId'),number:val('number'),date:val('date'),service:val('service'),description:val('description'),amount,discount,tax,total:Math.max(0,amount-discount+tax),notes:val('notes')}; if(isInv){obj.paid=Number(val('paid'));}else{obj.status=val('status')} upsert(type,obj); setPage(type)})}
function paymentForm(invoiceId=''){const open=state.invoices.filter(i=>invoiceStatus(i)==='Open'); const chosen=invoiceId || open[0]?.id || ''; app().innerHTML=formWrap('Record Payment',`<label class="full">Invoice<select id="invoiceId">${open.map(i=>`<option value="${i.id}" ${chosen===i.id?'selected':''}>${customerName(i.customerId)} — Invoice #${i.number} — ${money(invoiceBalance(i))} due</option>`).join('')}</select></label><label>Payment Date<input type="date" id="payDate" value="${new Date().toISOString().slice(0,10)}"></label><label>Amount<input type="number" step="0.01" id="payAmount" value="${chosen?invoiceBalance(state.invoices.find(i=>i.id===chosen)):0}"></label><label>Method<input id="method" placeholder="Cash, check, card"></label>`,()=>{const inv=state.invoices.find(i=>i.id===val('invoiceId')); if(!inv) return; const amount=Number(val('payAmount')); inv.paid=Number(inv.paid||0)+amount; state.payments.push({id:uid('pay'),invoiceId:inv.id,customerId:inv.customerId,date:val('payDate'),amount,method:val('method')}); save(); setPage('invoices', invoiceStatus(inv)==='Paid'?'paid':'open')})}
function jobForm(id){const j=state.jobs.find(x=>x.id===id)||{}; app().innerHTML=formWrap(id?'Edit Job':'New Job',`<label>Customer<select id="customerId">${customerOptions(j.customerId)}</select></label><label>Job Title<input id="title" value="${j.title||''}"></label><label>Scheduled Date<input type="date" id="date" value="${j.date||''}"></label><label class="full">Notes<textarea id="notes">${j.notes||''}</textarea></label>`,()=>{upsert('jobs',{id:id||uid('job'),customerId:val('customerId'),title:val('title'),date:val('date'),notes:val('notes')}); setPage('jobs','scheduled')})}
function approveEstimate(id){const e=state.estimates.find(x=>x.id===id); if(!e)return; e.status='Approved'; const date=prompt('Enter scheduled date as YYYY-MM-DD'); if(date){state.jobs.push({id:uid('job'),customerId:e.customerId,title:e.service||'Approved estimate job',date,notes:e.notes||e.description||'',estimateNumber:e.number})} save(); setPage('jobs','scheduled')}
function reports(){const monthly={}; state.payments.forEach(p=>{const d=new Date(`${p.date}T12:00:00`); const key=d.toLocaleDateString(undefined,{month:'long',year:'numeric'}); monthly[key]=(monthly[key]||0)+Number(p.amount||0)}); const max=Math.max(1,...Object.values(monthly)); app().innerHTML=`<div class="section-title"><h2>Reports</h2></div><div class="card"><h3>Monthly Revenue</h3><div class="report-bars">${Object.entries(monthly).map(([m,v])=>`<div><div class="muted">${m} — ${money(v)}</div><div class="bar-wrap"><div class="bar" style="width:${Math.max(8,v/max*100)}%">${money(v)}</div></div></div>`).join('')||'<div class="empty">No payments recorded yet.</div>'}</div></div>`}
function formWrap(title,fields,onSave){setTimeout(()=>document.getElementById('saveBtn').onclick=onSave,0);return `<div class="section-title"><h2>${title}</h2><button class="btn secondary" onclick="setPage('home')">Home</button></div><div class="card"><div class="form">${fields}<div class="actions full"><button class="btn primary" id="saveBtn">Save</button><button class="btn" onclick="render()">Cancel</button></div></div></div>`}

function esc(v){return String(v??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
function printRecord(type,id){
  const r=state[type].find(x=>x.id===id); if(!r) return;
  const isInv=type==='invoices'; const cust=state.customers.find(c=>c.id===r.customerId)||{};
  const subtotal=Number(r.amount||0), discount=Number(r.discount||0), tax=Number(r.tax||0), total=Number(r.total||Math.max(0,subtotal-discount+tax));
  const paid=isInv?Number(r.paid||0):0, bal=isInv?Math.max(0,total-paid):total;
  const payments=state.payments.filter(p=>p.invoiceId===r.id);
  app().innerHTML=`<div class="no-print-actions actions"><button class="btn" onclick="setPage('${type}')">Back to ${isInv?'Invoices':'Estimates'}</button><button class="btn primary" onclick="window.print()">Print / Save PDF</button><button class="btn secondary" onclick="setPage('home')">Home</button></div>
  <section class="print-area"><div class="print-doc">
    <div class="print-head">
      <div class="print-company"><div class="print-logo">W</div><div><h1>Westlake Tree Experts</h1><p>(610) 291-1176 · bwestlake@business.com</p><p>30 Ivy Ln, Douglassville, PA 19464</p></div></div>
      <div class="print-meta"><h2>${isInv?'Invoice':'Estimate'}</h2><p><b>#${esc(r.number)}</b></p><p>${fmtDate(r.date)}</p><p>${isInv?`Status: ${invoiceStatus(r)}`:`Status: ${estimateStatus(r)}`}</p></div>
    </div>
    <div class="print-grid">
      <div class="print-box"><h3>Bill To</h3><b>${esc(cust.name||customerName(r.customerId))}</b><p>${esc(cust.phone||'')}</p><p>${esc(cust.email||'')}</p><p>${esc(cust.propertyAddress||'')}</p></div>
      <div class="print-box"><h3>Service Information</h3><p><b>Service:</b> ${esc(r.service||'')}</p><p><b>Description:</b> ${esc(r.description||'')}</p><p><b>Property:</b> ${esc(cust.propertyAddress||'')}</p></div>
    </div>
    <table class="print-table"><thead><tr><th>Service / Work Description</th><th>Amount</th></tr></thead><tbody><tr><td><b>${esc(r.service||'Service')}</b><br>${esc(r.description||r.notes||'Tree / lawn service work')}</td><td>${money(subtotal)}</td></tr></tbody></table>
    <div class="print-totals"><div><span>Subtotal</span><span>${money(subtotal)}</span></div><div><span>Discount</span><span>-${money(discount)}</span></div><div><span>Tax</span><span>${money(tax)}</span></div><div class="grand"><span>Total</span><span>${money(total)}</span></div>${isInv?`<div><span>Paid</span><span>${money(paid)}</span></div><div class="grand"><span>Balance Due</span><span>${money(bal)}</span></div>`:''}</div>
    <div class="print-bottom">
      <div class="print-box"><h3>Payment Information</h3><p>Please make checks payable to Westlake Tree Experts.</p>${isInv?`<p><b>Balance Due:</b> ${money(bal)}</p>${payments.length?`<p><b>Payments:</b> ${payments.map(p=>`${fmtDate(p.date)} ${money(p.amount)} ${esc(p.method||'')}`).join('; ')}</p>`:''}`:`<p>This estimate is valid for 30 days unless otherwise noted.</p>`}</div>
      <div class="print-box"><h3>Customer Approval / Signature</h3><div class="signature-line"></div><p>Signature</p><div class="signature-line"></div><p>Date</p></div>
    </div>
    ${r.notes?`<div class="print-box" style="margin-top:8px"><h3>Notes</h3><div class="print-notes">${esc(r.notes)}</div></div>`:''}
  </div></section>`;
}

function val(id){return document.getElementById(id)?.value || ''} function upsert(type,obj){const idx=state[type].findIndex(x=>x.id===obj.id); if(idx>=0) state[type][idx]={...state[type][idx],...obj}; else state[type].push(obj); save()} function del(type,id){if(confirm('Delete this item?')){state[type]=state[type].filter(x=>x.id!==id);save();render()}} function nextNumber(type){return String(1000+state[type].length+1)}
render();
